# Generated by Django 3.1 on 2020-08-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ghost_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastroast',
            name='user_post',
            field=models.CharField(default='', max_length=280),
        ),
    ]
