# Generated by Django 3.1 on 2020-08-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ghost_post', '0002_auto_20200819_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boastroast',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='boastroast',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boastroast',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
